import pandas as pd

dados = [

    # ── CANDIDATURA E ADMISSÃO
    {"categoria": "admissão", "pergunta": "Como me candidatar à Universidade de Aveiro?", "resposta": "A candidatura à UA é feita através do portal nacional da DGES (www.dges.gov.pt) para o 1.º ciclo (licenciatura), usando as notas do Ensino Secundário e os exames nacionais. Para mestrados (2.º ciclo) e doutoramentos (3.º ciclo), a candidatura é feita diretamente no portal da UA (www.ua.pt/pt/candidatura). Existem também regimes especiais como Maiores de 23 anos, Titulares de Cursos Superiores e Estudantes Internacionais.", "link": "https://www.ua.pt/pt/candidatura"},
    {"categoria": "admissão", "pergunta": "Quais são as fases de candidatura ao 1.º ciclo na UA?", "resposta": "O acesso ao 1.º ciclo (licenciatura) tem normalmente três fases nacionais em julho/agosto, geridas pela DGES. Em cada fase, o candidato pode indicar até seis pares instituição/curso por ordem de preferência. A colocação é feita por ordem decrescente de nota de candidatura, até esgotar as vagas de cada curso.", "link": "https://www.dges.gov.pt/pt/pagina/candidatura-ao-ensino-superior"},
    {"categoria": "admissão", "pergunta": "Como me candidatar a um mestrado na UA?", "resposta": "A candidatura a mestrado na UA é feita diretamente no portal da UA (www.ua.pt/pt/candidatura/2-ciclo). Geralmente é necessário ter uma licenciatura na área ou afim, submeter carta de motivação, curriculum vitae e cartas de recomendação. Os prazos e requisitos específicos variam por curso — consulte a página de cada mestrado.", "link": "https://www.ua.pt/pt/candidatura/2-ciclo"},
    {"categoria": "admissão", "pergunta": "Posso candidatar-me à UA pelo regime Maiores de 23 anos?", "resposta": "Sim. O regime Maiores de 23 anos destina-se a candidatos com 23 anos ou mais que não possuam habilitação de acesso ao ensino superior. A UA realiza provas de avaliação de capacidade (geralmente uma prova escrita e entrevista) específicas para cada curso. As inscrições para estas provas são feitas no portal da UA.", "link": "https://www.ua.pt/pt/candidatura/maiores-23"},
    {"categoria": "admissão", "pergunta": "A UA aceita estudantes internacionais?", "resposta": "Sim. A UA tem um programa específico para estudantes internacionais, incluindo candidaturas fora dos contingentes nacionais. Os estudantes internacionais podem candidatar-se via portal da UA. Existe apoio dedicado pelo Gabinete de Relações Internacionais para questões de visto, alojamento e integração.", "link": "https://www.ua.pt/pt/estudantes-internacionais"},

    # ── CURSOS E DEPARTAMENTOS
    {"categoria": "departamentos", "pergunta": "Quais são os departamentos da Universidade de Aveiro?", "resposta": "A UA está organizada em 16 departamentos: Biologia; Ciências Sociais, Políticas e do Território; Comunicação e Arte; Economia, Gestão, Engenharia Industrial e Turismo; Educação e Psicologia; Electrónica, Telecomunicações e Informática (DETI); Engenharia Civil; Engenharia de Materiais e Cerâmica; Engenharia Mecânica; Engenharia Química; Física; Geociências; Línguas e Culturas; Matemática; Química; e Ciências Médicas. Cada departamento fica num edifício específico no campus de Santiago, em Aveiro.", "link": "https://www.ua.pt/pt/departamentos"},
    {"categoria": "departamentos", "pergunta": "Onde fica o curso de Engenharia Informática na UA?", "resposta": "A Licenciatura e o Mestrado em Engenharia de Computadores e Telemática (ECT) e o Mestrado em Engenharia Informática são lecionados no Departamento de Electrónica, Telecomunicações e Informática (DETI), localizado no edifício DETI no campus de Santiago, Aveiro. O DETI fica próximo do edifício do Complexo Pedagógico.", "link": "https://www.ua.pt/pt/deti"},
    {"categoria": "departamentos", "pergunta": "Onde fica o curso de Gestão na UA?", "resposta": "Os cursos de Gestão e Economia são lecionados no Departamento de Economia, Gestão, Engenharia Industrial e Turismo (DEGEIT), no campus de Santiago. O DEGEIT fica no edifício Ílhavo (edifício 3) do campus.", "link": "https://www.ua.pt/pt/degeit"},
    {"categoria": "departamentos", "pergunta": "Onde fica o curso de Medicina na UA?", "resposta": "O curso de Medicina é lecionado pelo Departamento de Ciências Médicas (DCM), em parceria com o Hospital Infante D. Pedro (Centro Hospitalar do Baixo Vouga). O departamento fica no edifício das Ciências da Saúde no campus de Santiago.", "link": "https://www.ua.pt/pt/dcm"},
    {"categoria": "departamentos", "pergunta": "Quais são os cursos de licenciatura disponíveis na UA?", "resposta": "A UA oferece mais de 40 licenciaturas, incluindo: Biologia, Bioquímica, Engenharia Civil, Engenharia de Computadores e Telemática, Engenharia Eletrónica e Telecomunicações, Engenharia Mecânica, Engenharia Química, Física, Gestão, Economia, Línguas e Relações Empresariais, Matemática, Química, Comunicação e Cultura, Turismo, Enfermagem, Medicina, Psicologia, Ciências da Educação, entre outros. Consulte www.ua.pt/pt/cursos para a lista completa.", "link": "https://www.ua.pt/pt/cursos"},

    # ── MATRÍCULA
    {"categoria": "matrícula", "pergunta": "Como fazer a matrícula na UA após a colocação?", "resposta": "Após a colocação, a matrícula é feita online no portal académico da UA (paco.ua.pt) dentro do prazo indicado no edital de colocação (geralmente 2 a 3 dias úteis). É necessário submeter digitalizações dos documentos exigidos (CC/BI, habilitações, foto) e pagar a primeira prestação de propinas. Falhar o prazo implica perda do lugar.", "link": "https://www.ua.pt/pt/matricula"},
    {"categoria": "matrícula", "pergunta": "O que é o PACO?", "resposta": "O PACO (Portal Académico Online) é o sistema de gestão académica da UA, acessível em paco.ua.pt. É através do PACO que o aluno faz matrículas, inscrições em unidades curriculares, consulta notas, pede certidões, acede ao horário e gere o seu percurso académico.", "link": "https://paco.ua.pt"},
    {"categoria": "matrícula", "pergunta": "Como renovar a matrícula na UA para o ano seguinte?", "resposta": "A renovação de matrícula é feita anualmente no PACO (paco.ua.pt) no início de cada ano letivo (geralmente setembro). O aluno deve confirmar a inscrição nas unidades curriculares que pretende frequentar e garantir que as propinas do ano anterior estão pagas.", "link": "https://paco.ua.pt"},

    # ── PROPINAS E BOLSAS
    {"categoria": "propinas", "pergunta": "Quanto custam as propinas na UA?", "resposta": "As propinas para cursos nacionais financiados estão definidas por lei: o valor máximo anual é 697,50 € para licenciaturas e mestrados integrados (em 2024/25). O pagamento pode ser feito numa única prestação com desconto, ou em prestações mensais de outubro a julho. Cursos internacionais e não financiados têm propinas diferentes.", "link": "https://www.ua.pt/pt/propinas"},
    {"categoria": "bolsas", "pergunta": "Como pedir bolsa de estudo na UA?", "resposta": "As bolsas de estudo são atribuídas pelos Serviços de Ação Social da UA (SAS/UA). A candidatura é feita online no portal da Direção-Geral do Ensino Superior (bolsas.dges.gov.pt) entre julho e novembro. A bolsa cobre propinas e pode incluir subsídio de alojamento e alimentação, conforme a situação económica do agregado familiar.", "link": "https://www.ua.pt/pt/sas/bolsas"},
    {"categoria": "bolsas", "pergunta": "Que outros apoios sociais existem para alunos da UA?", "resposta": "Os SAS/UA oferecem: bolsas de estudo, alojamento em residências universitárias, refeições subsidiadas nas cantinas, apoio de saúde (consultas de medicina geral, psicologia, enfermagem), e apoio de emergência para situações imprevistas. Contacto: sas@ua.pt ou presencialmente nos SAS no campus.", "link": "https://www.ua.pt/pt/sas"},

    # ── CALENDÁRIO ACADÉMICO
    {"categoria": "calendário", "pergunta": "Como é organizado o ano letivo na UA?", "resposta": "O ano letivo na UA divide-se em dois semestres. O 1.º semestre decorre de meados de setembro a janeiro (com época de exames em janeiro/fevereiro). O 2.º semestre decorre de fevereiro a junho (com época de exames em junho/julho). Existe ainda uma época especial de exames em setembro. O calendário exato é publicado anualmente no site da UA.", "link": "https://www.ua.pt/pt/calendario-academico"},
    {"categoria": "calendário", "pergunta": "Quando são as épocas de exames na UA?", "resposta": "Existem três épocas de exames na UA: Época Normal (janeiro/fevereiro para o 1.º semestre; junho/julho para o 2.º semestre), Época de Recurso (fevereiro para o 1.º semestre; julho para o 2.º semestre) e Época Especial (setembro, para alunos finalistas ou com situações especiais aprovadas). As datas concretas estão no PACO e no site de cada departamento.", "link": "https://www.ua.pt/pt/calendario-academico"},

    # ── CAMPUS E LOCALIZAÇÃO
    {"categoria": "campus", "pergunta": "Onde fica o campus da Universidade de Aveiro?", "resposta": "O campus principal da UA fica em Santiago, Aveiro, Portugal (Campus Universitário de Santiago, 3810-193 Aveiro). É um campus universitário com edifícios departamentais, biblioteca, cantinas, residências, museu e lago. Fica a cerca de 10 minutos a pé da estação de comboios de Aveiro.", "link": "https://www.ua.pt/pt/campus"},
    {"categoria": "campus", "pergunta": "Como chegar à UA de comboio ou autocarro?", "resposta": "De comboio: a estação de Aveiro fica a cerca de 10-15 minutos a pé do campus. De autocarro: os STCP/Transdev têm linhas que passam junto ao campus. De carro: há parques de estacionamento no campus (alguns gratuitos, outros pagos). A UA também tem serviço de bicicletas partilhadas no campus.", "link": "https://www.ua.pt/pt/campus"},

    # ── ALOJAMENTO
    {"categoria": "alojamento", "pergunta": "Como conseguir alojamento nas residências da UA?", "resposta": "O alojamento nas residências universitárias da UA é gerido pelos SAS/UA. A candidatura é feita online nos SAS entre maio e julho, sendo prioritários os alunos deslocados e com menor rendimento. As residências oferecem quartos individuais e duplos com wi-fi, lavandaria e zonas comuns. Caso não haja vaga, os SAS têm uma bolsa de alojamentos privados verificados.", "link": "https://www.ua.pt/pt/sas/residencias"},
    {"categoria": "alojamento", "pergunta": "Qual o custo das residências universitárias da UA?", "resposta": "Os preços das residências dos SAS/UA variam conforme o tipo de quarto e rendimento do aluno (bolseiros têm valores reduzidos). Em 2024/25, os valores mensais rondam os 150 € a 250 € para bolseiros e 250 € a 400 € para não bolseiros. Consulte os SAS para os valores exatos do ano corrente.", "link": "https://www.ua.pt/pt/sas/residencias"},

    # ── ALIMENTAÇÃO
    {"categoria": "alimentação", "pergunta": "Onde posso comer no campus da UA?", "resposta": "A UA tem várias cantinas e bares geridos pelos SAS/UA. As principais são: Cantina de Santiago, Cantina do Crasto, Cantina da Universidade e vários bares departamentais. Os preços são subsidiados: refeições completas custam cerca de 2,90 € para estudantes (bolseiros podem ter valores reduzidos). Há também cafetarias privadas no campus.", "link": "https://www.ua.pt/pt/sas/alimentacao"},

    # ── BIBLIOTECA
    {"categoria": "biblioteca", "pergunta": "Como funciona a biblioteca da UA?", "resposta": "A Biblioteca da UA (SBIDM) fica no edifício central do campus e está aberta a todos os estudantes. Oferece espaços de estudo individual e em grupo, empréstimo de livros, acesso a bases de dados científicas (IEEE, Scopus, Web of Science, etc.), impressão e digitalização. O acesso é feito com o cartão de estudante. Horário: normalmente 9h-21h em dias úteis.", "link": "https://www.ua.pt/pt/sbidm"},

    # ── SERVIÇOS ACADÉMICOS
    {"categoria": "serviços", "pergunta": "Como pedir certidões e declarações na UA?", "resposta": "Certidões e declarações (matrícula, aproveitamento, frequência) são pedidas online através do PACO (paco.ua.pt) em 'Secretaria Virtual'. A maioria das declarações fica disponível para download em formato digital em 24-48 horas úteis. Documentos que necessitem de assinatura física devem ser pedidos presencialmente nos Serviços Académicos.", "link": "https://paco.ua.pt"},
    {"categoria": "serviços", "pergunta": "Como obter o cartão de estudante da UA?", "resposta": "O cartão de estudante é emitido automaticamente após a matrícula. O cartão físico é levantado nos Serviços Académicos da UA (edifício do Reitoral). Serve como identificação no campus, acesso à biblioteca, descontos em transportes e comércio local. Em caso de perda, deve ser reportado e pedir um novo nos Serviços Académicos.", "link": "https://www.ua.pt/pt/cartao-estudante"},
    {"categoria": "serviços", "pergunta": "Qual o horário e contacto dos Serviços Académicos da UA?", "resposta": "Os Serviços Académicos da UA ficam no edifício do Reitoral, no campus de Santiago. Horário de atendimento presencial: segunda a sexta, 9h30-12h30 e 14h-16h30. Contacto: sa@ua.pt | Tel: +351 234 370 200. Muitos serviços estão disponíveis online no PACO sem necessidade de deslocação.", "link": "https://www.ua.pt/pt/servicos-academicos"},

    # ── MOBILIDADE INTERNACIONAL
    {"categoria": "mobilidade", "pergunta": "Como participar no programa Erasmus na UA?", "resposta": "A UA tem protocolos Erasmus+ com mais de 400 universidades europeias. Para candidatar: aceda ao portal da UA > Internacional > Erasmus. A candidatura é feita normalmente em janeiro/fevereiro para o ano seguinte, através do sistema de mobilidade da UA. É necessário ter aproveitamento mínimo (geralmente 60 ECTS concluídos) e nível de língua B2 no idioma do país de destino. A UA atribui bolsa Erasmus mensal para ajuda nos custos.", "link": "https://www.ua.pt/pt/erasmus"},
    {"categoria": "mobilidade", "pergunta": "A UA tem acordos de mobilidade fora da Europa?", "resposta": "Sim. Além do Erasmus europeu, a UA tem protocolos com universidades no Brasil, EUA, Canadá, Japão, China e países africanos lusófonos. Estes programas são geridos pelo Gabinete de Relações Internacionais (GRI) da UA. Contacto: internacional@ua.pt.", "link": "https://www.ua.pt/pt/internacional"},

    # ── SAÚDE E APOIO
    {"categoria": "saúde", "pergunta": "Que serviços de saúde existem para estudantes da UA?", "resposta": "Os SAS/UA oferecem serviços de saúde gratuitos ou de baixo custo para estudantes: consultas de medicina geral, enfermagem, psicologia, nutrição e medicina dentária. O Serviço de Saúde fica no edifício dos SAS no campus. É necessário marcação prévia pelo e-mail saude.sas@ua.pt ou pelo telefone dos SAS.", "link": "https://www.ua.pt/pt/sas/saude"},
    {"categoria": "saúde", "pergunta": "Como aceder ao apoio psicológico na UA?", "resposta": "A UA oferece apoio psicológico gratuito a todos os estudantes através do Serviço de Apoio Psicológico dos SAS. O atendimento é confidencial. Para marcar consulta: envie e-mail para psicologia.sas@ua.pt ou dirija-se presencialmente aos SAS. Em situações de crise, a UA tem também protocolo com linha de apoio psicológico 24h.", "link": "https://www.ua.pt/pt/apoio-psicologico"},

    # ── DESPORTO
    {"categoria": "desporto", "pergunta": "Que atividades desportivas existem na UA?", "resposta": "A UA tem a Associação Académica de Aveiro (AAUAv) que gere um vasto leque de atividades desportivas: ginásio, piscina, campos de futebol, ténis, basquete, voleibol, atletismo, desportos aquáticos, artes marciais e muito mais. A inscrição é feita na AAUAv com valores reduzidos para estudantes. A UA participa também nos Campeonatos Nacionais Universitários (CNU).", "link": "https://www.ua.pt/pt/desporto"},

    # ── VIDA ACADÉMICA
    {"categoria": "vida académica", "pergunta": "O que é a AAUAv e como me associar?", "resposta": "A Associação Académica da Universidade de Aveiro (AAUAv) é a associação estudantil que representa os alunos da UA. Gere a praxe académica, o desporto universitário, atividades culturais, bares académicos e defende os interesses dos estudantes. Qualquer estudante da UA pode associar-se na sede da AAUAv no campus de Santiago.", "link": "https://www.aauav.pt"},
    {"categoria": "vida académica", "pergunta": "Como funciona a praxe académica na UA?", "resposta": "A praxe académica na UA é organizada pela AAUAv e é voluntária. Consiste em rituais de integração dos caloiros (novos alunos) conduzidos pelos veteranos, com o objetivo de promover a camaradagem e a identidade académica. A UA tem um Código de Praxe que proíbe qualquer forma de humilhação ou coação. A participação nunca é obrigatória.", "link": "https://www.aauav.pt"},

    # ── DISSERTAÇÃO E CONCLUSÃO
    {"categoria": "dissertação", "pergunta": "Como submeter a dissertação de mestrado na UA?", "resposta": "A dissertação de mestrado deve ser submetida no RIA (Repositório Institucional da UA) em formato PDF, após aprovação pelo orientador e pelo júri. O processo é: (1) submeter o pedido de provas no PACO; (2) aguardar a marcação do júri pelos Serviços Académicos; (3) realizar a defesa pública; (4) após aprovação, submeter a versão final no RIA (ria.ua.pt) dentro de 30 dias. O Departamento emite depois a certidão de conclusão.", "link": "https://www.ua.pt/pt/dissertacao"},
    {"categoria": "dissertação", "pergunta": "Qual o prazo para concluir o mestrado na UA?", "resposta": "Os mestrados na UA têm geralmente duração de 2 anos (4 semestres). O Regulamento de Estudos Pós-Graduados permite que o aluno fique inscrito até 4 anos. Passado esse prazo, pode pedir prorrogação justificada aos Serviços Académicos. Recomenda-se contactar o orientador logo no início para definir o cronograma da dissertação.", "link": "https://www.ua.pt/pt/regulamento-estudos"},
    {"categoria": "conclusão", "pergunta": "Como pedir o diploma na UA?", "resposta": "Após concluir todas as unidades curriculares e defender a dissertação/projeto (se aplicável), o diploma é emitido automaticamente pelos Serviços Académicos. Para acelerar o processo, pode pedir formalmente nos Serviços Académicos ou via PACO. O Suplemento ao Diploma (documento europeu que descreve o percurso académico) é emitido gratuitamente junto com o diploma.", "link": "https://www.ua.pt/pt/diploma"},
    {"categoria": "conclusão", "pergunta": "O que é o Suplemento ao Diploma da UA?", "resposta": "O Suplemento ao Diploma é um documento europeu emitido em português e inglês que descreve detalhadamente o percurso académico do estudante: curso, departamento, unidades curriculares, notas, sistema de classificação e perfil profissional. É emitido gratuitamente pela UA junto com o diploma e é muito valorizado por empregadores europeus e para reconhecimento de graus no estrangeiro.", "link": "https://www.ua.pt/pt/diploma"},

    # ── REGULAMENTOS
    {"categoria": "regulamentos", "pergunta": "Onde encontro o regulamento académico da UA?", "resposta": "O Regulamento de Estudos da UA está disponível no Diário da República e no site da UA em www.ua.pt/pt/regulamento-estudos. Define as regras sobre inscrições, avaliação, transição de ano, prescrição, equivalências, regime de trabalhador-estudante e outros aspetos do percurso académico. Em caso de dúvida, os Serviços Académicos podem esclarecer.", "link": "https://www.ua.pt/pt/regulamento-estudos"},
    {"categoria": "regulamentos", "pergunta": "O que acontece se reprovar muitas vezes na UA? (prescrição)", "resposta": "O regime de prescrição na UA determina que um estudante pode perder o estatuto de estudante se não cumprir requisitos mínimos de aproveitamento. As regras variam por ciclo de estudos, mas em geral: no 1.º ciclo, o aluno não pode estar inscrito mais de n+2 anos (onde n é a duração normal do curso). Verifique o Regulamento de Estudos ou contacte os Serviços Académicos para o seu caso específico.", "link": "https://www.ua.pt/pt/regulamento-estudos"},

    # ── GERAL
    {"categoria": "geral", "pergunta": "O que é a Universidade de Aveiro?", "resposta": "A Universidade de Aveiro (UA) é uma universidade pública portuguesa fundada em 1973, localizada em Aveiro. É conhecida pela sua arquitetura moderna e inovadora no campus de Santiago. Tem cerca de 15.000 estudantes, 16 departamentos e vários institutos de investigação. É consistentemente classificada entre as melhores universidades portuguesas, com forte ligação à indústria e à investigação científica.", "link": "https://www.ua.pt"},
    {"categoria": "geral", "pergunta": "Qual o e-mail e contacto geral da Universidade de Aveiro?", "resposta": "Contactos gerais da UA: Site: www.ua.pt | Tel: +351 234 370 200 | Morada: Universidade de Aveiro, Campus Universitário de Santiago, 3810-193 Aveiro, Portugal. Serviços Académicos: sa@ua.pt | SAS: sas@ua.pt | Internacional: internacional@ua.pt", "link": "https://www.ua.pt/pt/contactos"},
    {"categoria": "geral", "pergunta": "Como aceder ao e-mail institucional da UA?", "resposta": "Todos os estudantes da UA têm um e-mail institucional no formato nmec@ua.pt (número mecanográfico). O acesso é feito em webmail.ua.pt usando as credenciais do PACO. Este e-mail é o canal oficial de comunicação com a UA e deve ser verificado regularmente, pois é usado para informações sobre matrículas, resultados e avisos importantes.", "link": "https://webmail.ua.pt"},
    {"categoria": "geral", "pergunta": "O que é o eLearning da UA?", "resposta": "O eLearning da UA (elearning.ua.pt) é a plataforma Moodle da universidade onde os professores disponibilizam materiais de apoio, fichas de trabalho, testes e onde ocorrem fóruns de discussão. O acesso é feito com as credenciais do PACO. Cada unidade curricular tem uma página no eLearning.", "link": "https://elearning.ua.pt"},
]

df = pd.DataFrame(dados, columns=["categoria", "pergunta", "resposta", "link"])
df.to_csv("assistente_aluno_ua.csv", index=False, encoding="utf-8-sig")

print(f"CSV criado com sucesso!")
print(f"Total de entradas: {len(df)}")
print(f"Colunas: {list(df.columns)}")
print(f"\nDistribuicao por categoria:")
print(df["categoria"].value_counts().to_string())
